Repository lovelymahor/StudyMatePlus, pull requests merged in 2025-08, with the labels that each got.

#4 Added Landing Page
  client/package-lock.json
  client/package.json
  client/src/components/Navbar.css
  client/src/components/Navbar.js
  client/src/pages/Home.css
  client/src/pages/Home.js
  client/src/pages/PYQs.js
  client/src/pages/Syllabus.js
Labels: documentation, enhancement, gssoc2025, level 3

#8 Added About Us Section
  client/src/App.js
  client/src/components/Navbar.js
  client/src/pages/About.css
  client/src/pages/About.js
Labels: enhancement, good first issue, gssoc2025, level 2

#9 Implemented basic UI for pyq's page
  client/src/pages/PYQs.css
  client/src/pages/PYQs.js
Labels: good first issue, gssoc25, level 1

#24 update the size and gap in flexing navbar in mobile devices
  client/src/components/Navbar.css
  package-lock.json
Labels: good first issue, gssoc25, level 1

#35 Enhance Footer with Social Links, Sticky Option, and Auto-Updating Year #33
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/pages/Home.css
  client/src/pages/Home.js
Labels: documentation, gssoc25, level 2

#43 [FIX]: #41 Low contrast: Browse Syllabus button blends with page
  client/src/pages/Home.css
  client/src/pages/Home.js
Labels: documentation, gssoc25, level 1

#48 Enhanced Feature Cards with Neon Glow Effect in "Why Choose StudyMatePlus" section
  client/src/pages/Home.css
Labels: enhancement, gssoc25, level 1

#47 [FIX]: #40 Inconsistent page transitions across routes
  client/src/pages/About.js
  client/src/pages/Analytics.js
  client/src/pages/Notes.jsx
  client/src/pages/PYQs.js
  client/src/pages/Syllabus.js
Labels: documentation, gssoc25, level 2

#53 Added faq page
  client/src/App.js
  client/src/components/Navbar.js
  client/src/pages/Faq.css
  client/src/pages/Faq.js
Labels: documentation, gssoc25, level 2

#59 Enhance Subject Filter and Download Functionality in Analytics Component
  client/src/pages/Analytics.js
Labels: documentation, gssoc25, level 2

#55 Feature :Added the Mindmaps Section
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/Navbar.js
  client/src/pages/MindMapEditor.css
  client/src/pages/MindMapEditor.js
Labels: enhancement, gssoc25, level 3

#70 Made the submit feedback form
  client/src/App.js
  client/src/pages/Feedback.js
  client/src/pages/SubmitFeedback.css
  client/src/pages/SubmitFeedback.js
Labels: documentation, gssoc25, level 2

#72 Made the interface for profile page
  client/src/App.js
  client/src/components/Navbar.css
  client/src/components/Navbar.js
  client/src/pages/Profile.css
  client/src/pages/Profile.js
Labels: gssoc25, level 2
