Repository lovelymahor/StudyMatePlus, pull requests merged in 2025-09, with the labels that each got.

#77 Save feedback modal submissions to MongoDB Atlas
  StudyMatePlus.code-workspace
  client/public/index.html
  client/src/components/FeedbackModal.css
  client/src/components/FeedbackModal.js
  client/src/pages/Feedback.css
  client/src/pages/Feedback.js
  server/index.js
  server/package-lock.json
  server/package.json
Labels: enhancement, gssoc25, level 2

#75 feat: add scroll to top buttons to pages
  client/src/pages/About.js
  client/src/pages/Analytics.js
  client/src/pages/Faq.js
  client/src/pages/Feedback.js
  client/src/pages/MindMapEditor.js
  client/src/pages/Notes.jsx
  client/src/pages/PYQs.js
  client/src/pages/Syllabus.js
Labels: gssoc25, level 2

#78 feat: Implement full-website responsive design
  client/src/components/FeedbackModal.css
  client/src/components/Navbar.css
  client/src/components/Navbar.js
  client/src/pages/Analytics.css
  client/src/pages/Faq.css
  client/src/pages/Feedback.js
  client/src/pages/MindMapEditor.css
  client/src/pages/PYQs.css
Labels: documentation, gssoc25, level 2

#79 Fixed scroll to top distortion on all pages
  client/src/pages/About.js
  client/src/pages/Analytics.js
  client/src/pages/Contact.js
  client/src/pages/Contribute.js
  client/src/pages/Faq.js
  client/src/pages/Feedback.js
  client/src/pages/Home.css
  client/src/pages/Home.js
  client/src/pages/MindMapEditor.js
  client/src/pages/PYQs.js
  client/src/pages/Privacy.js
  client/src/pages/Profile.js
  client/src/pages/ScrollToTop.css
Labels: good first issue, gssoc25, level 1
